include: package:pedantic_mono/analysis_options.yaml
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - lib/**/*.g.dart
linter:
  rules:
    top_level_function_literal_block: false