name: experimental_site
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"


dependencies:
  auto_route: ^4.0.1
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  flutter_svg: ^1.0.3
  freezed: ^2.0.3+1
  hooks_riverpod: ^1.0.4

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.0.3
  pedantic_mono:

flutter:
  uses-material-design: true
  assets:
    - assets/pic/

